from __future__ import annotations

from typing import Any


THEMES: tuple[dict[str, str], ...] = (
    {"id": "uniform", "name": "制服诱惑", "lead": "ai"},
    {"id": "teacher_student", "name": "成人师生play", "lead": "ai"},
    {"id": "boss_subordinate", "name": "上司下属play", "lead": "ai"},
    {"id": "maid_master", "name": "女仆主人play", "lead": "ai"},
    {"id": "doctor_checkup", "name": "医生检查play", "lead": "ai"},
    {"id": "lady_butler", "name": "大小姐管家play", "lead": "player"},
    {"id": "secretary_boss", "name": "秘书老板play", "lead": "ai"},
    {"id": "landlord_tenant", "name": "房东房客play", "lead": "ai"},
    {"id": "tutor_student", "name": "成人补课play", "lead": "ai"},
    {"id": "stranger_lovers", "name": "陌生恋人play", "lead": "ai"},
    {"id": "office_affair", "name": "办公室偷情", "lead": "ai"},
    {"id": "ntr_fantasy", "name": "NTR幻想", "lead": "ai"},
    {"id": "affair", "name": "偷情play", "lead": "ai"},
    {"id": "owner_pet", "name": "主人宠物play", "lead": "ai"},
    {"id": "role_reversal", "name": "身份倒置", "lead": "player"},
    {"id": "gap_moe", "name": "反差诱惑", "lead": "ai"},
    {"id": "secret_lovers", "name": "秘密恋人", "lead": "ai"},
    {"id": "dom_sub", "name": "支配臣服", "lead": "ai"},
    {"id": "light_training", "name": "轻度调教", "lead": "ai"},
    {"id": "light_bondage", "name": "轻度束缚", "lead": "ai"},
    {"id": "blindfold_training", "name": "蒙眼调教", "lead": "ai"},
    {"id": "handcuff_bondage", "name": "手铐束缚", "lead": "ai"},
    {"id": "collar_leash", "name": "项圈牵引", "lead": "ai"},
    {"id": "remote_toy", "name": "玩具遥控", "lead": "ai"},
    {"id": "orgasm_control", "name": "高潮控制", "lead": "ai"},
    {"id": "edging", "name": "寸止调教", "lead": "ai"},
    {"id": "ejaculation_control", "name": "射精管理", "lead": "ai"},
    {"id": "creampie_permission", "name": "中出许可", "lead": "ai"},
    {"id": "facial_permission", "name": "颜射许可", "lead": "ai"},
    {"id": "fluid_marking", "name": "体液标记", "lead": "ai"},
    {"id": "toy_overload", "name": "玩具失控", "lead": "ai"},
    {"id": "dirty_talk", "name": "淫语调教", "lead": "ai"},
    {"id": "wet_training", "name": "湿身调教", "lead": "ai"},
    {"id": "shame_service", "name": "羞耻侍奉", "lead": "ai"},
    {"id": "nipple_training", "name": "乳首调教", "lead": "ai"},
    {"id": "forbidden_words", "name": "禁语调教", "lead": "ai"},
    {"id": "command_shame", "name": "命令羞耻", "lead": "ai"},
    {"id": "verbal_shame", "name": "言语羞耻", "lead": "ai"},
    {"id": "kneeling_punishment", "name": "罚跪调教", "lead": "ai"},
    {"id": "spanking", "name": "打屁股惩罚", "lead": "ai"},
    {"id": "exposure_edge", "name": "露出边缘", "lead": "ai"},
    {"id": "obedience_training", "name": "服从训练", "lead": "ai"},
    {"id": "reward_punishment", "name": "奖惩调教", "lead": "ai"},
    {"id": "no_ejaculation", "name": "禁射调教", "lead": "ai"},
    {"id": "claim_marking", "name": "标记占有", "lead": "ai"},
    {"id": "begging_permission", "name": "求饶许可", "lead": "ai"},
    {"id": "shame_display", "name": "羞耻展示", "lead": "ai"},
    {"id": "strong_command", "name": "强势命令", "lead": "ai"},
    {"id": "jealous_punishment", "name": "吃醋惩罚", "lead": "ai"},
    {"id": "praise_training", "name": "夸奖调教", "lead": "ai"},
    {"id": "body_worship", "name": "身体崇拜", "lead": "ai"},
    {"id": "sensory_deprivation", "name": "感官剥夺", "lead": "ai"},
    {"id": "temperature_play", "name": "温度play", "lead": "ai"},
    {"id": "makeup_sex", "name": "和好炮", "lead": "ai"},
    {"id": "reunion", "name": "久别重逢", "lead": "ai"},
    {"id": "photographer_model", "name": "摄影师模特play", "lead": "ai"},
    {"id": "coach_student", "name": "教练学员play", "lead": "ai"},
    {"id": "vampire_human", "name": "吸血鬼人类play", "lead": "player"},
    {"id": "knight_princess", "name": "骑士公主play", "lead": "ai"},
    {"id": "old_shanghai", "name": "民国旧上海play", "lead": "ai"},
    {"id": "palace", "name": "古代宫廷play", "lead": "ai"},
    {"id": "neighbor_affair", "name": "邻居偷情play", "lead": "ai"},
    {"id": "phone_sex", "name": "电话做爱", "lead": "ai"},
    {"id": "remote_orders", "name": "远程指令play", "lead": "ai"},
    {"id": "alpha_rut", "name": "Alpha易感期", "lead": "ai"},
    {"id": "temporary_mark", "name": "临时标记", "lead": "ai"},
    {"id": "possessive", "name": "强占有欲", "lead": "ai"},
    {"id": "heat_knotting", "name": "发情期交配成结", "lead": "ai"},
)


SLOTS: dict[str, dict[str, Any]] = {
    "theme": {
        "label": "玩法",
        "options": [item["name"] for item in THEMES],
    },
    "prop": {
        "label": "道具惩罚",
        "options": (
            "领带",
            "眼罩",
            "皮带",
            "丝袜",
            "黑丝袜",
            "白衬衫",
            "制服外套",
            "情趣内衣",
            "束缚带",
            "束腕带",
            "丝带",
            "缎带",
            "项圈",
            "牵引绳",
            "冰块",
            "润滑液",
            "避孕套",
            "震动棒",
            "跳蛋",
            "跳蛋遥控器",
            "手铐",
            "口球",
            "乳夹",
            "小皮拍",
            "戒尺",
            "铃铛项圈",
            "按摩棒",
            "口红",
            "发绳",
            "腿环",
            "吊袜带",
            "透明胶带",
            "低温蜡烛",
            "羽毛棒",
            "分腿器",
            "震动子弹",
            "双头假阳具",
            "穿戴式玩具",
            "吸乳器",
            "阴蒂吸吮器",
            "网袜",
            "皮革手套",
            "围巾",
            "蜂蜜",
            "奶油",
            "冰棒",
            "电动牙刷",
            "尾巴肛塞",
        ),
    },
    "limit": {
        "label": "限制",
        "options": (
            "另外一个玩家没允许不准亲嘴",
            "另外一个玩家没允许不准换姿势",
            "另外一个玩家没允许不准插入",
            "另外一个玩家没允许不准加速",
            "另外一个玩家没允许不准射",
            "另外一个玩家没允许不准中出",
            "一小时内不准中出",
            "中出前只能学狗叫",
            "想中出必须先求另外一个玩家三次",
            "想射前必须说自己忍不住了",
            "射之前必须等另外一个玩家点头",
            "中出前必须戴着项圈求允许",
            "想中出必须先被寸止一次",
            "没学会求饶不准射",
            "另外一个玩家第一次高潮前不准中出",
            "另外一个玩家没高潮前不准射",
            "另外一个玩家说停必须立刻停",
            "不准只顾自己爽",
            "不准弄疼另外一个玩家",
            "不准跳过前戏",
            "不准直接插入",
            "不准提前摘掉眼罩",
            "不准提前解开束缚",
            "不准摘掉自己的项圈",
            "不准把节奏交给另外一个玩家前先射",
            "不准让另外一个玩家自己动手",
            "不准在另外一个玩家脸红前停手",
            "不准在另外一个玩家说可以前收尾",
            "不准提前擦掉体液",
            "不准关灯逃避被看",
            "不准遮住自己的表情",
            "不准把羞耻任务推给另外一个玩家",
            "不准拒绝另外一个玩家的命令",
            "不准提前脱掉裸身围裙",
            "不准提前摘掉铃铛项圈",
            "没被另外一个玩家寸止过不准射",
            "不准在另外一个玩家满意前结束",
            "不准在另外一个玩家满意前讨价还价",
            "不准没有被另外一个玩家验收就收尾",
            "不准没有申请就换玩法",
            "不准在被允许前摘下道具",
            "不准把高潮留给自己先爽",
            "不准在另外一个玩家命令外擅自加速",
            "不准用沉默糊弄另外一个玩家",
            "不准提前结束惩罚",
            "没有报备不准射",
            "没有求许可不准中出",
            "另外一个玩家没说停之前不准偷懒",
            "另外一个玩家没说够了不准离开",
            "另外一个玩家没验收不准摘项圈",
            "想换动作必须先申请",
            "不准跳过夸另外一个玩家",
            "不准只用一种节奏糊弄过去",
            "不准在另外一个玩家害羞躲开时立刻放过对方",
            "不准关掉半公开的紧张感",
            "另外一个玩家每次发抖都要被你说出来",
            "抽到的道具必须真的用上",
            "不准在另外一个玩家声音软下来前结束",
            "不准把想做的话咽回去",
            "不准只顾动作不哄对方",
            "不准在对方主动靠近前假装正经",
            "易感期里不准冷处理另外一个玩家",
            "临时标记前必须先把另外一个玩家哄软",
            "成结以后不准立刻退开",
            "不准把强占有欲说成装没事",
        ),
    },
    "task": {
        "label": "任务",
        "options": (
            "穿裸身围裙伺候对方",
            "戴项圈听对方命令",
            "被对方蒙眼调戏",
            "被对方用领带牵着亲",
            "被对方手交到快射再停",
            "被对方素股磨到快射",
            "给对方舔到高潮",
            "用手把对方弄到腿软",
            "用玩具让对方高潮一次",
            "只准用嘴取悦对方",
            "先让对方高潮一次",
            "让对方决定今天的称呼",
            "让对方决定最后射在哪里",
            "被对方用口红写上标记",
            "把跳蛋遥控器交给对方",
            "穿吊袜带给对方看",
            "戴铃铛项圈亲对方",
            "把内裤交给对方保管",
            "被对方命令说想要",
            "被对方寸止到发抖",
            "被对方允许后才能射",
            "先让对方舒服到发软",
            "把对方亲到主动求继续",
            "让对方半穿衣被亲到脸红",
            "给蒙眼的对方舔到高潮",
            "把对方伺候到腿软",
            "让对方高潮后继续抱着亲",
            "让对方说出最想被怎么弄",
            "哄到对方自己说想要",
            "射在哪里必须听对方决定",
            "收尾必须先把对方哄舒服",
            "念一句羞耻台词给对方听",
            "被对方检查有没有真的忍住",
            "结束前必须把对方哄到满意",
            "犯规一次就接受对方追加惩罚",
            "让对方用一句话决定惩罚内容",
            "射前必须向对方完整报备",
            "被对方寸止一次再继续",
            "把最想要的事说给对方听",
            "让对方验收今天有没有乖",
            "穿裸身围裙给对方做夜宵",
            "戴着项圈等对方发令",
            "把手腕交给对方绑住",
            "让对方检查今天有没有偷爽",
            "被对方夸乖以后才能继续",
            "用淫语把想要的事说清楚",
            "用夸奖把对方哄到主动靠近",
            "在镜子前让对方看清你有多想要对方",
            "用冰块和吻把对方弄到发抖",
            "隔着衣服磨到对方先受不了",
            "让对方坐在你脸上慢慢爽",
            "把对方抱到腿上含着不动",
            "用三种速度把对方弄到分不清节奏",
            "让对方听见你忍不住的声音",
            "用电话指令让对方一步步配合",
            "让对方在半公开的地方被你抱紧",
            "只用手指和舌头把对方伺候到腿抖",
            "把对方全身反应都说给对方听",
            "给对方戴上蒙眼后慢慢检查哪里最敏感",
            "让对方用一个动作决定今晚先做什么",
            "让对方在易感期里被你抱到安静下来",
            "在对方后颈留下临时标记",
            "用强占有欲把对方圈在怀里哄软",
            "发情期里和对方交配到成结",
        ),
    },
    "pose": {
        "label": "姿势",
        "options": (
            "后入式",
            "站立后入",
            "跪趴",
            "正常位",
            "传教士位",
            "屈膝后入",
            "抱起插入",
            "女上位",
            "反骑乘",
            "背对骑乘",
            "面对坐姿",
            "背坐式",
            "腿架肩",
            "双腿高抬",
            "抱腿位",
            "站立位",
            "坐莲式",
            "对坐位",
            "跪姿位",
            "趴跪位",
            "侧卧位",
            "侧卧后入",
            "俯卧后入",
            "跪坐位",
            "并腿位",
            "侧入式",
            "膝上骑乘",
            "M字开腿",
            "69式",
            "坐脸",
            "乳交",
            "腿交",
            "椅子位",
            "折叠按压",
            "蹲骑",
            "推车姿势",
            "趴压",
            "壁尻",
            "浴缸骑乘",
            "面对面站立",
            "背后抱立",
            "含着不动",
            "成结",
        ),
    },
    "place": {
        "label": "地点",
        "options": (
            "酒店床上",
            "浴室墙边",
            "车后座",
            "试衣间隔间",
            "办公桌边",
            "教室讲台边",
            "厨房台面",
            "沙发上",
            "落地镜前",
            "阳台门边",
            "玄关地垫",
            "洗手台前",
            "会议桌上",
            "图书馆角落",
            "楼梯间转角",
            "床尾",
            "门后",
            "落地窗前",
            "浴缸里",
            "淋浴间水声里",
            "KTV包厢沙发",
            "电影院最后一排",
            "停车场车里",
            "天台雨后",
            "衣帽间镜前",
            "按摩床上",
            "海边露台",
            "帐篷睡袋里",
            "温室角落",
            "水族馆玻璃前",
            "化妆台前",
            "深夜便利店仓库",
            "小木屋壁炉旁",
        ),
    },
}


REWARD_CARD_PASS = "pass"
REWARD_CARD_LABELS = {
    REWARD_CARD_PASS: "Pass 卡",
}


REVIEW_PENALTY_CARDS: tuple[dict[str, Any], ...] = (
    {
        "id": "reverse_invitation",
        "name": "反向诱惑",
        "type": "review",
        "task": "向另外一个玩家提交一条成人向指令，内容必须和当前主题有关，并且是你希望另外一个玩家对你做的事。",
        "submission": "写下完整指令，不要只写关键词。",
        "pass_result": "另外一个玩家选择【通过】后，任务完成，游戏继续。",
        "reject_prompt": "另外一个玩家认为你的指令太含糊，请重新写得更具体。",
        "pass_allowed": True,
    },
    {
        "id": "ranked_confession",
        "name": "排序坦白",
        "type": "review",
        "task": "按敏感程度从低到高，列出你现在最不想被另外一个玩家针对的五个身体部位或状态弱点。",
        "submission": "写成一段完整描述，排序要清楚。",
        "pass_result": "另外一个玩家选择【通过】后，任务完成，游戏继续。",
        "reject_prompt": "另外一个玩家认为你的坦白不够具体，请重新提交。",
        "pass_allowed": True,
    },
    {
        "id": "embarrassing_lines",
        "name": "羞耻台词大放送",
        "type": "review",
        "task": "根据当前主题，向另外一个玩家写三句撒娇的话。",
        "submission": "提交三句话，不要只写关键词。",
        "pass_result": "另外一个玩家选择【通过】后，任务完成，游戏继续。",
        "reject_prompt": "另外一个玩家认为你撒娇得不够，请重新提交。",
        "pass_allowed": True,
    },
    {
        "id": "masturbation_statement",
        "name": "自慰陈述",
        "type": "review",
        "task": "你需要按当前主题进行自慰，请描述自慰过程。",
        "submission": "写一段完整的自慰过程描述，不要只写“完成了”。",
        "pass_result": "另外一个玩家选择【通过】后，任务完成，游戏继续。",
        "reject_prompt": "另外一个玩家认为你的任务完成度不够，请重新描述自慰过程。",
        "pass_allowed": True,
    },
)


CHOICE_PENALTY_CARDS: tuple[dict[str, Any], ...] = (
    {
        "id": "prop_or_rule",
        "name": "道具还是限制",
        "type": "choice",
        "prompt": "选择一项惩罚。",
        "pass_allowed": True,
        "choices": (
            {"id": "add_prop", "label": "新增一个道具惩罚", "effect": {"kind": "add_status", "slot": "prop", "duration_type": "until_clear"}},
            {"id": "add_limit", "label": "新增一条限制", "effect": {"kind": "add_status", "slot": "limit", "duration_type": "until_clear"}},
        ),
    },
    {
        "id": "new_or_upgrade_prop",
        "name": "加新还是升档",
        "type": "choice",
        "prompt": "选择一项道具惩罚。",
        "pass_allowed": True,
        "choices": (
            {"id": "add_prop", "label": "新增一个道具惩罚", "effect": {"kind": "add_status", "slot": "prop", "duration_type": "until_clear"}},
            {"id": "upgrade_prop_level", "label": "现有道具惩罚档位上调一级", "requires": {"status_slot": "prop"}, "effect": {"kind": "upgrade_status_level", "slot": "prop", "delta": 1}},
        ),
    },
    {
        "id": "back_or_prop",
        "name": "退格还是上道具",
        "type": "choice",
        "prompt": "选择一项惩罚。",
        "pass_allowed": True,
        "choices": (
            {"id": "move_back_2", "label": "后退 2 格", "effect": {"kind": "move", "steps": -2}},
            {"id": "add_prop", "label": "新增一个道具惩罚", "effect": {"kind": "add_status", "slot": "prop", "duration_type": "until_clear"}},
        ),
    },
    {
        "id": "lose_action_or_upgrade",
        "name": "停步还是升档",
        "type": "choice",
        "prompt": "选择一项惩罚。",
        "pass_allowed": True,
        "choices": (
            {"id": "lose_action", "label": "失去 1 次行动权", "effect": {"kind": "add_block", "slot": "prop", "actions": 1}},
            {"id": "upgrade_prop_level", "label": "现有道具惩罚档位上调一级", "requires": {"status_slot": "prop"}, "effect": {"kind": "upgrade_status_level", "slot": "prop", "delta": 1}},
        ),
    },
    {
        "id": "pose_or_place",
        "name": "姿势还是地点",
        "type": "choice",
        "prompt": "选择一项状态惩罚。",
        "pass_allowed": True,
        "choices": (
            {"id": "add_pose", "label": "新增一个姿势状态", "effect": {"kind": "add_status", "slot": "pose", "duration_type": "until_finish"}},
            {"id": "add_place", "label": "新增一个地点状态", "effect": {"kind": "add_status", "slot": "place", "duration_type": "until_clear"}},
        ),
    },
    {
        "id": "rule_or_task",
        "name": "限制还是任务",
        "type": "choice",
        "prompt": "选择一项惩罚。",
        "pass_allowed": True,
        "choices": (
            {"id": "add_limit", "label": "新增一条限制", "effect": {"kind": "add_status", "slot": "limit", "duration_type": "until_clear"}},
            {"id": "add_task", "label": "新增一个任务状态", "effect": {"kind": "add_status", "slot": "task", "duration_type": "until_clear"}},
        ),
    },
    {
        "id": "heavy_prop_or_back",
        "name": "重罚二选一",
        "type": "choice",
        "prompt": "选择一项重惩罚。",
        "pass_allowed": True,
        "choices": (
            {"id": "add_prop_and_lose_action", "label": "新增道具惩罚并失去 1 次行动权", "effect": {"kind": "add_status_and_block", "slot": "prop", "actions": 1}},
            {"id": "move_back_3", "label": "后退 3 格", "effect": {"kind": "move", "steps": -3}},
        ),
    },
    {
        "id": "upgrade_or_pose",
        "name": "升档还是姿势",
        "type": "choice",
        "prompt": "选择一项惩罚。",
        "pass_allowed": True,
        "choices": (
            {"id": "upgrade_prop_level", "label": "现有道具惩罚档位上调一级", "requires": {"status_slot": "prop"}, "effect": {"kind": "upgrade_status_level", "slot": "prop", "delta": 1}},
            {"id": "add_pose", "label": "新增一个姿势状态", "effect": {"kind": "add_status", "slot": "pose", "duration_type": "until_finish"}},
        ),
    },
)
